### ISSUE TITLE
Weird behaviour

### ISSUE THREAD

**Issue by XvenDeR** [omgugly/anti-shuffle#2]
Hey, I have found something.

I press Shift to take drivers seat, but when I get out and back again to car, it teleports me to passenger seat.

Video:
https://streamable.com/4nt2dx

**Comment by omgugly** [comment]
thanks for the heads up on this, yeah i put the wrong task id into the update. fixed it now, tested and all should work normal again. my fault and again, thanks for letting me know. grab the new files and it should be good
