### ISSUE TITLE
[Suggestion] Nice shuffling between seats

### ISSUE THREAD

**Issue by XvenDeR** [omgugly/anti-shuffle#3]
I have a suggestion to make a perfect shuffling between seats with this native:

TaskShuffleToNextVehicleSeat
https://runtime.fivem.net/doc/natives/?_0x7AA80209BDA643EB

```
TaskShuffleToNextVehicleSeat(
	ped --[[ Ped ]], 
	vehicle --[[ Vehicle ]]
)
```
_Makes the specified ped shuffle to the next vehicle seat.  
The ped MUST be in a vehicle and the vehicle parameter MUST be the ped's current vehicle._ 

This would work very nice from driver seat to passenger.

**Comment by omgugly** [comment]
i'm looking into this, check my comment under your pull request
