### ISSUE TITLE
allowKeyShuffle unexpected behaviour

### ISSUE THREAD

**Issue by iSentrie** [omgugly/anti-shuffle#7]
I think it's not intended to work like this so I will open a issue for it.

**Issue:**
• Even if `allowKeyShuffle = false` you can shuffle with [Shift], but only from passenger seat to driver seat.

**Comment by omgugly** [comment]
no, this is intended functionality. the original purpose of the script was to stop the player from automatically shuffling into the driver seat from passenger but allow them to manually slide over if/when they want by pressing shift.
